// <auto-generated />
using LeagueAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LeagueAPI.Migrations
{
    [DbContext(typeof(LeagueContext))]
    [Migration("20191114201926_addpos img")]
    partial class addposimg
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LeagueAPI.Models.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CharacterId");

                    b.Property<string>("Items");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Builds");

                    b.HasData(
                        new { Id = 1, CharacterId = 1, Items = "Death's Dance, BloodThirster, Blade of the Ruine King, Mercurial Scimitar, Berserker Greaves, Hectech Gunblade", Name = "Life Steal" }
                    );
                });

            modelBuilder.Entity("LeagueAPI.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AtkType");

                    b.Property<string>("DmgType");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<int>("PositionId");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Characters");

                    b.HasData(
                        new { Id = 1, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/1.png", Name = "Aatrox", PositionId = 1 },
                        new { Id = 2, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/2.png", Name = "Ahri", PositionId = 3 },
                        new { Id = 3, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/3.png", Name = "Akali", PositionId = 3 },
                        new { Id = 4, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/4.png", Name = "Alistar", PositionId = 5 },
                        new { Id = 5, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/5.png", Name = "Amumu", PositionId = 2 },
                        new { Id = 6, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/6.png", Name = "Anivia", PositionId = 3 },
                        new { Id = 7, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/7.png", Name = "Annie", PositionId = 3 },
                        new { Id = 8, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/8.png", Name = "Ashe", PositionId = 2 },
                        new { Id = 9, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/9.png", Name = "Aurrelion Sol", PositionId = 3 },
                        new { Id = 10, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/10.png", Name = "Azir", PositionId = 3 },
                        new { Id = 11, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/11.png", Name = "Bard", PositionId = 5 },
                        new { Id = 12, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/12.png", Name = "Blitzcrank", PositionId = 5 },
                        new { Id = 13, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/13.png", Name = "Brand", PositionId = 3 },
                        new { Id = 14, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/14.png", Name = "Braum", PositionId = 5 },
                        new { Id = 15, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/15.png", Name = "Caitlyn", PositionId = 4 },
                        new { Id = 16, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/16.png", Name = "Camille", PositionId = 1 },
                        new { Id = 17, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/17.png", Name = "Cassilopeia", PositionId = 3 },
                        new { Id = 18, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/18.png", Name = "Cho’Gath", PositionId = 1 },
                        new { Id = 19, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/19.png", Name = "Corki", PositionId = 4 },
                        new { Id = 20, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/20.png", Name = "Darius", PositionId = 1 },
                        new { Id = 21, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/21.png", Name = "Diana", PositionId = 3 },
                        new { Id = 22, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/22.png", Name = "Dr. Mundo", PositionId = 2 },
                        new { Id = 23, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/23.png", Name = "Draven", PositionId = 4 },
                        new { Id = 24, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/24.png", Name = "Ekko", PositionId = 2 },
                        new { Id = 25, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/25.png", Name = "Elise", PositionId = 2 },
                        new { Id = 26, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/26.png", Name = "Evelynn", PositionId = 2 },
                        new { Id = 27, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/27.png", Name = "Ezreal", PositionId = 4 },
                        new { Id = 28, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/28.png", Name = "Fiddlesticks", PositionId = 2 },
                        new { Id = 29, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/29.png", Name = "Fiora", PositionId = 1 },
                        new { Id = 30, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/30.png", Name = "Fizz", PositionId = 3 },
                        new { Id = 31, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/31.png", Name = "Galio", PositionId = 3 },
                        new { Id = 32, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/32.png", Name = "Gangplank", PositionId = 1 },
                        new { Id = 33, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/33.png", Name = "Garen", PositionId = 1 },
                        new { Id = 34, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/34.png", Name = "Gnar", PositionId = 1 },
                        new { Id = 35, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/35.png", Name = "Gragas", PositionId = 2 },
                        new { Id = 36, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/36.png", Name = "Graves", PositionId = 5 },
                        new { Id = 37, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/37.png", Name = "Hecarim", PositionId = 2 },
                        new { Id = 38, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/38.png", Name = "Heimerdinger", PositionId = 3 },
                        new { Id = 39, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/39.png", Name = "Illaoi", PositionId = 1 },
                        new { Id = 40, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/40.png", Name = "Irelia", PositionId = 1 },
                        new { Id = 41, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/41.png", Name = "Ivern", PositionId = 2 },
                        new { Id = 42, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/42.png", Name = "Janna", PositionId = 5 },
                        new { Id = 43, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/43.png", Name = "Jarvan IV", PositionId = 2 },
                        new { Id = 44, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/44.png", Name = "Jayce", PositionId = 1 },
                        new { Id = 45, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/45.png", Name = "Jax", PositionId = 1 },
                        new { Id = 46, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/46.png", Name = "Jhin", PositionId = 4 },
                        new { Id = 47, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/47.png", Name = "Jinx", PositionId = 4 },
                        new { Id = 48, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/48.png", Name = "Kai’Sa", PositionId = 4 },
                        new { Id = 49, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/49.png", Name = "Kalista", PositionId = 4 },
                        new { Id = 50, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/50.png", Name = "Karma", PositionId = 5 },
                        new { Id = 51, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/51.png", Name = "Karthas", PositionId = 2 },
                        new { Id = 52, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/52.png", Name = "Kassadin", PositionId = 3 },
                        new { Id = 53, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/53.png", Name = "Katarina", PositionId = 3 },
                        new { Id = 54, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/54.png", Name = "Kayle", PositionId = 1 },
                        new { Id = 55, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/55.png", Name = "Kayn", PositionId = 2 },
                        new { Id = 56, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/56.png", Name = "Kennen", PositionId = 1 },
                        new { Id = 57, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/57.png", Name = "Kha’Zix", PositionId = 2 },
                        new { Id = 58, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/58.png", Name = "Kindred", PositionId = 2 },
                        new { Id = 59, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/59.png", Name = "Kled", PositionId = 1 },
                        new { Id = 60, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/60.png", Name = "Kog’Maw", PositionId = 4 },
                        new { Id = 61, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/61.png", Name = "LeBlanc", PositionId = 3 },
                        new { Id = 62, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/62.png", Name = "Lee Sin", PositionId = 2 },
                        new { Id = 63, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/63.png", Name = "Leona", PositionId = 5 },
                        new { Id = 64, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/64.png", Name = "Lissandra", PositionId = 3 },
                        new { Id = 65, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/65.png", Name = "Lucian", PositionId = 4 },
                        new { Id = 66, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/66.png", Name = "Lulu", PositionId = 5 },
                        new { Id = 67, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/67.png", Name = "Lux", PositionId = 5 },
                        new { Id = 68, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/68.png", Name = "Malphite", PositionId = 1 },
                        new { Id = 69, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/69.png", Name = "Malzahar", PositionId = 3 },
                        new { Id = 70, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/70.png", Name = "Maokai", PositionId = 1 },
                        new { Id = 71, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/71.png", Name = "Master Yi", PositionId = 2 },
                        new { Id = 72, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/72.png", Name = "Miss Fortune", PositionId = 4 },
                        new { Id = 73, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/73.png", Name = "Mordekaiser", PositionId = 1 },
                        new { Id = 74, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/74.png", Name = "Morgana", PositionId = 5 },
                        new { Id = 75, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/75.png", Name = "Nami", PositionId = 5 },
                        new { Id = 76, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/76.png", Name = "Nasus", PositionId = 1 },
                        new { Id = 77, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/77.png", Name = "Nautilus", PositionId = 5 },
                        new { Id = 78, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/78.png", Name = "Neeko", PositionId = 3 },
                        new { Id = 79, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/79.png", Name = "Nidalee", PositionId = 2 },
                        new { Id = 80, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/80.png", Name = "Nocturne", PositionId = 2 },
                        new { Id = 81, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/81.png", Name = "Nunu", PositionId = 2 },
                        new { Id = 82, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/82.png", Name = "Olaf", PositionId = 2 },
                        new { Id = 83, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/83.png", Name = "Orianna", PositionId = 3 },
                        new { Id = 84, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/84.png", Name = "Ornn", PositionId = 1 },
                        new { Id = 85, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/85.png", Name = "Pantheon", PositionId = 2 },
                        new { Id = 86, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/86.png", Name = "Poppy", PositionId = 1 },
                        new { Id = 87, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/87.png", Name = "Pyke", PositionId = 5 },
                        new { Id = 88, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/88.png", Name = "Qiyana", PositionId = 3 },
                        new { Id = 89, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/89.png", Name = "Quinn", PositionId = 1 },
                        new { Id = 90, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/90.png", Name = "Rakan", PositionId = 5 },
                        new { Id = 91, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/91.png", Name = "Rammus", PositionId = 2 },
                        new { Id = 92, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/92.png", Name = "Rek’Sai", PositionId = 2 },
                        new { Id = 93, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/93.png", Name = "Renekton", PositionId = 1 },
                        new { Id = 94, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/94.png", Name = "Rengar", PositionId = 2 },
                        new { Id = 95, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/95.png", Name = "Riven", PositionId = 1 },
                        new { Id = 96, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/96.png", Name = "Rumble", PositionId = 1 },
                        new { Id = 97, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/97.png", Name = "Ryze", PositionId = 3 },
                        new { Id = 98, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/98.png", Name = "Sejuani", PositionId = 2 },
                        new { Id = 99, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/99.png", Name = "Senna", PositionId = 5 },
                        new { Id = 100, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/100.png", Name = "Shaco", PositionId = 5 },
                        new { Id = 101, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/101.png", Name = "Shen", PositionId = 1 },
                        new { Id = 102, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/102.png", Name = "Shyvana", PositionId = 2 },
                        new { Id = 103, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/103.png", Name = "Singed", PositionId = 1 },
                        new { Id = 104, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/104.png", Name = "Rumble", PositionId = 1 },
                        new { Id = 105, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/105.png", Name = "Sion", PositionId = 1 },
                        new { Id = 106, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/106.png", Name = "Sivir", PositionId = 5 },
                        new { Id = 107, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/107.png", Name = "Skarner", PositionId = 5 },
                        new { Id = 108, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/108.png", Name = "Sona", PositionId = 5 },
                        new { Id = 109, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/109.png", Name = "Soraka", PositionId = 5 },
                        new { Id = 110, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/110.png", Name = "Swain", PositionId = 1 },
                        new { Id = 111, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/111.png", Name = "Sylas", PositionId = 3 },
                        new { Id = 112, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/112.png", Name = "Syndra", PositionId = 3 },
                        new { Id = 113, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/113.png", Name = "Tahm Kench", PositionId = 5 },
                        new { Id = 114, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/114.png", Name = "Taliyah", PositionId = 2 },
                        new { Id = 115, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/115.png", Name = "Talon", PositionId = 5 },
                        new { Id = 116, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/116.png", Name = "Teemo", PositionId = 5 },
                        new { Id = 117, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/117.png", Name = "Thresh", PositionId = 5 },
                        new { Id = 118, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/118.png", Name = "Tristana", PositionId = 4 },
                        new { Id = 119, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/119.png", Name = "Trundle", PositionId = 2 },
                        new { Id = 120, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/120.png", Name = "Tryndamere", PositionId = 1 },
                        new { Id = 121, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/121.png", Name = "Twisted Fate", PositionId = 3 },
                        new { Id = 122, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/122.png", Name = "Twitch", PositionId = 4 },
                        new { Id = 123, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/123.png", Name = "Udyr", PositionId = 2 },
                        new { Id = 124, AtkType = "Ranged", DmgType = "Ability Damage", Image = "/images/124.png", Name = "Urgot", PositionId = 1 },
                        new { Id = 125, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/125.png", Name = "Varus", PositionId = 4 },
                        new { Id = 126, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/126.png", Name = "Vayne", PositionId = 4 },
                        new { Id = 127, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/127.png", Name = "Veigar", PositionId = 3 },
                        new { Id = 128, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/128.png", Name = "Velkoz", PositionId = 3 },
                        new { Id = 129, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/129.png", Name = "Vi", PositionId = 2 },
                        new { Id = 130, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/130.png", Name = "Viktor", PositionId = 3 },
                        new { Id = 131, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/131.png", Name = "Vladmir", PositionId = 1 },
                        new { Id = 132, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/132.png", Name = "Volibear", PositionId = 2 },
                        new { Id = 133, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/133.png", Name = "Warwick", PositionId = 2 },
                        new { Id = 134, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/134.png", Name = "Wukong", PositionId = 2 },
                        new { Id = 135, AtkType = "Ranged", DmgType = "Attack Damage", Image = "/images/135.png", Name = "Xayah", PositionId = 4 },
                        new { Id = 136, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/136.png", Name = "Xerath", PositionId = 3 },
                        new { Id = 137, AtkType = "Melee", DmgType = "Ability Power", Image = "/images/137.png", Name = "Xin Zhao", PositionId = 2 },
                        new { Id = 138, AtkType = "Melee", DmgType = "Attack", Image = "/images/138.png", Name = "Yasuo", PositionId = 3 },
                        new { Id = 139, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/139.png", Name = "Yorick", PositionId = 1 },
                        new { Id = 140, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/140.png", Name = "Yuumi", PositionId = 5 },
                        new { Id = 141, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/141.png", Name = "Zac", PositionId = 2 },
                        new { Id = 142, AtkType = "Melee", DmgType = "Attack Damage", Image = "/images/142.png", Name = "Zed", PositionId = 3 },
                        new { Id = 143, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/143.png", Name = "Ziggs", PositionId = 3 },
                        new { Id = 144, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/144.png", Name = "Zilean", PositionId = 5 },
                        new { Id = 145, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/145.png", Name = "Zoe", PositionId = 3 },
                        new { Id = 146, AtkType = "Ranged", DmgType = "Ability Power", Image = "/images/146.png", Name = "Zyra", PositionId = 1 }
                    );
                });

            modelBuilder.Entity("LeagueAPI.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new { Id = 1, Image = "./images/TopLane.png", Name = "Top" },
                        new { Id = 2, Image = "./images/JungleLane.png", Name = "Jungle" },
                        new { Id = 3, Image = "./images/MiddleLane.png", Name = "Mid" },
                        new { Id = 4, Image = "./images/ADCLane.png", Name = "ADC" },
                        new { Id = 5, Image = "./images/SupportLane.png", Name = "Support" }
                    );
                });

            modelBuilder.Entity("LeagueAPI.Models.Build", b =>
                {
                    b.HasOne("LeagueAPI.Models.Character", "Character")
                        .WithMany("Builds")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LeagueAPI.Models.Character", b =>
                {
                    b.HasOne("LeagueAPI.Models.Position", "Position")
                        .WithMany("Characters")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
